export const CITIES = [
    "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Surat", "Pune", "Jaipur",
    "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Pimpri-Chinchwad", "Patna", "Vadodara",
    "Ghaziabad", "Ludhiana", "Agra", "Nashik", "Faridabad", "Meerut", "Rajkot", "Kalyan-Dombivli", "Vasai-Virar", "Varanasi",
    "Srinagar", "Aurangabad", "Dhanbad", "Amritsar", "Navi Mumbai", "Allahabad", "Ranchi", "Howrah", "Coimbatore", "Jabalpur",
    "London", "New York", "Tokyo", "Paris", "Berlin", "Sydney", "Dubai", "Singapore", "Moscow", "Toronto",
    "Los Angeles", "Chicago", "Houston", "Seoul", "Beijing", "Bangkok", "Istanbul", "Madrid", "Rome", "Amsterdam",
    "Vijayawada", "Guntur", "Nellore", "Tirupati", "Kakinada", "Rajahmundry", "Kurnool", "Anantapur", "Kadapa", "Eluru",
    "London", "New York", "Paris", "Tokyo", "Madrid", "Singapore", "Rome", "Dubai", "Berlin", "Barcelona", "Hong Kong", "Shanghai",
    "Los Angeles", "Chicago", "Seoul", "Mumbai", "Delhi", "Bengaluru", "Chennai", "Kolkata", "Hyderabad", "Ahmedabad", "Pune", "Denver",
    "Atlanta", "Nashville", "Austin", "Charlotte", "Portland", "Seattle", "Boston", "Jaipur", "Lucknow", "Surat", "Kochi", "Nagpur",
    "Indore", "Chandigarh", "Bhubaneswar", "Visakhapatnam", "Agra", "Patna", "Ludhiana", "Kanpur", "Vadodara", "Nashik", "Faridabad",
    "Ghaziabad", "Coimbatore", "Detroit", "Las Vegas", "Orlando", "St. Louis", "Memphis", "Kansas City", "Milwaukee", "Tucson", "Mysuru",
    "Udaipur", "Vijayawada", "Salem", "Mangaluru", "Varanasi", "Madurai", "Gwalior", "Jalandhar", "Dehradun", "Thrissur", "Tiruchirappalli",
    "Ahmednagar", "Alwar", "Akola", "Berhampur", "Bilaspur", "San Francisco", "Sydney", "Amsterdam", "Milan", "Toronto", "Frankfurt",
    "Jakarta", "Sao Paulo", "Mexico City", "Guangzhou", "Istanbul", "Shenzhen", "Buenos Aires", "Melbourne", "Santiago", "Warsaw",
    "Brussels", "Zurich", "Bangkok", "Kuala Lumpur", "Manila", "Ho Chi Minh City", "Hanoi", "Bogota", "Cape Town", "Athens",
    "Copenhagen", "Dublin", "Hamburg", "Lisbon", "Oslo", "Perth", "Adelaide", "Brisbane", "Montreal", "Vancouver", "Rio de Janeiro",
    "Cologne", "Vienna", "Munich", "Stockholm", "Warsaw", "Lyon", "Manchester", "Stuttgart", "Prague", "Budapest", "Bucharest",
    "Helsinki", "Sofia", "Belgrade", "Kiev", "Riyadh", "Doha", "Kuwait City", "Abu Dhabi", "Dalian", "Tianjin", "Chengdu", "Wuhan",
    "Nanjing", "Suzhou", "Xi'an", "Qingdao", "Zhengzhou", "Changsha", "Fuzhou", "Shijiazhuang", "Nanning", "Harbin", "Jinan", "Taiyuan",
    "Guiyang", "Hefei", "Foshan", "Wuxi", "Shenyang", "Ningbo", "Kunming", "Chongqing", "Xiamen", "Durban", "Johannesburg", "Cairo",
    "Nairobi", "Casablanca", "Accra", "Lagos", "Tunis", "Algiers", "Dar es Salaam", "Addis Ababa", "Mexico City", "Lima", "Santiago",
    "Bogota", "Buenos Aires", "Sao Paulo", "Rio de Janeiro", "Monterrey", "Guadalajara", "Caracas", "Montevideo", "Panama City",
    "Guatemala City", "Quito", "San Jose", "Tegucigalpa", "San Salvador", "Managua", "Cali", "Barranquilla", "Recife", "Salvador",
    "Porto Alegre", "Curitiba", "Brasilia", "La Paz", "Canberra", "Melbourne", "Sydney", "Perth", "Adelaide", "Brisbane", "Auckland",
    "Wellington"
];
